name = "PostPurchasePro"
client_id = "241e0c22c806c22aea6a9f3957f29484"

application_url = "https://revenuepulse-production.up.railway.app"
embedded = false

[access_scopes]
scopes = "read_orders, read_products, read_analytics"

[app_proxy]
url = "https://revenuepulse-production.up.railway.app"
subpath = "revenuepulse"
prefix = "apps"

[auth]
  redirect_urls = [
    "https://revenuepulse-production.up.railway.app/api/auth/callback",
    "https://revenuepulse-production.up.railway.app/api/auth/shopify/callback",
  ]

[webhooks]
api_version = "2024-01"

[pos]
enabled = false
embedded = false
