api_version = "2024-01"
name = "RevenuePulse Post Purchase"
[[extensions]]
name = "RevenuePulse Post Purchase"
type = "checkout_ui"
handle = "revenuepulse-post-purchase"

[[target.purchase.post.render]]
resource = "checkout"

[runtime]
name = "Checkout"
